### PR TITLE
log4js cleanup - a few places that had minor references to log4js, mostly in comments.

### PR DESCRIPTION
**Pull request by EricWasTakenMJD**

### CODE REVIEW

**Comment by EricWasTakenMJD** [comment]
This is broken waiting on a downstream issue.
See https://github.com/valtech-sd/rule-harvester/issues/46

**Review by valtech-le — APPROVED** [review]

**Comment by EricWasTakenMJD** [comment]
This now uses Coronado-Bridge 2.1.0 which eliminates the dependency on Log4JS and resolves the issue with this PR.

**Comment by EricWasTakenMJD** [comment]
Also bringing in a fix for https://github.com/valtech-sd/rule-harvester/issues/44

**Review by daniellmorris — APPROVED** [review]

**Pull request merged**
